;this file for FamiTone2 library generated by text2data tool

mega_man_style_1_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env2,@env6,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env4,@env7,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env5,@env8,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c4,$c4,$c5,$c5,$c6,$00,$04
@env2:
	.byte $c6,$c3,$c2,$c1,$c0,$00,$04
@env3:
	.byte $c6,$c3,$c0,$00,$02
@env4:
	.byte $cf,$04,$c0,$00,$02
@env5:
	.byte $c4,$02,$c5,$02,$c6,$03,$c0,$00,$06
@env6:
	.byte $c0,$c3,$00,$01
@env7:
	.byte $d2,$ce,$ca,$c6,$c2,$00,$04
@env8:
	.byte $cc,$cc,$c0,$00,$02


@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $80,$3c,$85,$32,$85,$38,$85,$3a,$85,$3c,$85,$32,$85,$38,$85,$3a
	.byte $85
@ref1:
	.byte $32,$8d,$32,$8d,$38,$8d,$3a,$8d
@ref2:
	.byte $4a,$85,$3c,$95,$4a,$89,$51,$4a,$85,$46,$85
@ref3:
	.byte $32,$95,$3c,$85,$38,$85,$32,$85,$38,$8d
@ref4:
	.byte $3a,$89,$32,$b1
@ref5:
	.byte $3a,$85,$01,$3a,$85,$01,$3a,$85,$3c,$8d,$40,$8d
	.byte $ff,$0b
	.word @ref2
	.byte $ff,$0a
	.word @ref3
@ref8:
	.byte $3a,$89,$32,$b1
@ref9:
	.byte $3a,$85,$01,$3a,$85,$01,$3a,$85,$40,$8d,$3c,$8d
@ref10:
	.byte $8a,$32,$85,$32,$85,$42,$85,$32,$85,$41,$33,$2e,$85,$32,$85,$40
	.byte $85
@ref11:
	.byte $32,$85,$32,$85,$42,$85,$32,$85,$40,$85,$32,$85,$2e,$85,$32,$85
@ref12:
	.byte $32,$85,$32,$85,$42,$85,$32,$85,$41,$33,$2e,$85,$32,$85,$40,$85
@ref13:
	.byte $80,$38,$85,$32,$85,$38,$85,$2e,$85,$30,$8d,$32,$8d
@ref14:
	.byte $8a,$32,$85,$32,$85,$42,$85,$32,$85,$40,$85,$2e,$85,$32,$85,$40
	.byte $85
	.byte $ff,$10
	.word @ref11
	.byte $ff,$10
	.word @ref12
@ref17:
	.byte $80,$38,$89,$32,$89,$2e,$85,$30,$8d,$32,$8d
@ref18:
	.byte $00,$85,$3c,$85,$38,$85,$33,$38,$89,$3c,$95
@ref19:
	.byte $39,$3d,$4a,$89,$42,$89,$3c,$8d,$38,$8d
@ref20:
	.byte $3c,$ad,$39,$01,$43,$3c,$81
@ref21:
	.byte $33,$3d,$43,$3d,$33,$3d,$43,$3d,$33,$3d,$43,$3d,$33,$3d,$43,$3c
	.byte $81
@ref22:
	.byte $00,$85,$46,$85,$4a,$85,$51,$4a,$89,$3c,$95
@ref23:
	.byte $43,$39,$32,$89,$38,$89,$42,$8d,$3c,$8d
@ref24:
	.byte $30,$89,$32,$89,$38,$95,$33,$01,$4b,$46,$81
@ref25:
	.byte $3d,$47,$4b,$47,$3d,$47,$4b,$47,$42,$89,$46,$89,$4a,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref26:
	.byte $80,$54,$85,$4a,$85,$50,$85,$52,$85,$54,$85,$4a,$85,$50,$85,$52
	.byte $85
@ref27:
	.byte $4a,$8d,$4a,$8d,$50,$8d,$52,$8d
@ref28:
	.byte $00,$85,$4a,$85,$3c,$95,$4a,$89,$51,$4a,$85
@ref29:
	.byte $46,$85,$32,$95,$3c,$85,$38,$85,$32,$85,$38,$85
@ref30:
	.byte $87,$3a,$89,$32,$a9
@ref31:
	.byte $87,$3a,$85,$01,$3a,$85,$01,$3a,$85,$3c,$8d,$40,$85
@ref32:
	.byte $87,$4a,$85,$3c,$95,$4a,$89,$51,$4a,$85
	.byte $ff,$0c
	.word @ref29
	.byte $ff,$05
	.word @ref30
@ref35:
	.byte $87,$3a,$85,$01,$3a,$85,$01,$3a,$85,$40,$8d,$3c,$85
@ref36:
	.byte $3c,$8d,$42,$85,$46,$85,$40,$85,$38,$8d,$3c,$85
@ref37:
	.byte $9f,$32,$8d,$38,$8d
@ref38:
	.byte $3c,$9d,$38,$9d
@ref39:
	.byte $42,$85,$3c,$85,$42,$85,$38,$85,$3a,$8d,$3c,$8d
	.byte $ff,$0c
	.word @ref36
	.byte $ff,$05
	.word @ref37
@ref42:
	.byte $3c,$9d,$38,$9d
@ref43:
	.byte $42,$89,$3c,$89,$38,$85,$3a,$8d,$3c,$8d
@ref44:
	.byte $3c,$85,$38,$85,$33,$38,$89,$3c,$95,$39,$3c,$81
@ref45:
	.byte $4a,$89,$42,$89,$3c,$95,$42,$8d
@ref46:
	.byte $46,$ad,$43,$01,$4a,$85
@ref47:
	.byte $9f,$46,$8d,$3c,$8d
@ref48:
	.byte $46,$85,$4a,$85,$51,$4a,$89,$3c,$95,$43,$38,$81
@ref49:
	.byte $32,$89,$38,$89,$42,$95,$46,$8d
@ref50:
	.byte $3a,$89,$3c,$89,$42,$95,$3d,$01,$54,$85
@ref51:
	.byte $9f,$4a,$89,$50,$89,$54,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref52:
	.byte $80,$3c,$95,$00,$85,$3c,$95,$00,$85
@ref53:
	.byte $32,$8b,$00,$32,$8d,$38,$8d,$88,$32,$85,$33,$32,$81
@ref54:
	.byte $80,$3c,$87,$00,$3d,$00,$85,$43,$01,$46,$85,$3c,$85,$42,$85,$3c
	.byte $83,$00
@ref55:
	.byte $3c,$87,$00,$3d,$00,$85,$43,$01,$46,$85,$3c,$85,$42,$85,$3c,$85
@ref56:
	.byte $32,$87,$00,$33,$00,$85,$39,$01,$3c,$85,$32,$85,$38,$85,$32,$83
	.byte $00
@ref57:
	.byte $32,$87,$00,$33,$00,$85,$39,$01,$3c,$85,$32,$85,$38,$85,$32,$85
@ref58:
	.byte $3c,$87,$00,$3d,$00,$85,$43,$01,$46,$85,$3c,$85,$42,$85,$3c,$83
	.byte $00
	.byte $ff,$10
	.word @ref55
	.byte $ff,$11
	.word @ref56
@ref61:
	.byte $32,$87,$00,$33,$00,$85,$39,$01,$40,$85,$88,$32,$85,$80,$3c,$85
	.byte $88,$32,$83,$00
@ref62:
	.byte $80,$33,$01,$33,$01,$42,$85,$3c,$85,$41,$3d,$39,$33,$2e,$85,$32
	.byte $83,$00
@ref63:
	.byte $33,$01,$33,$01,$42,$85,$3c,$85,$40,$85,$38,$85,$2e,$85,$32,$83
	.byte $00
@ref64:
	.byte $33,$01,$33,$01,$42,$85,$3c,$85,$41,$3d,$39,$33,$2e,$85,$32,$83
	.byte $00
@ref65:
	.byte $33,$01,$33,$01,$42,$85,$3c,$85,$3a,$85,$88,$33,$33,$80,$3c,$85
	.byte $88,$32,$83,$00
	.byte $ff,$11
	.word @ref62
	.byte $ff,$11
	.word @ref63
	.byte $ff,$11
	.word @ref64
@ref69:
	.byte $32,$89,$42,$89,$3c,$85,$3a,$85,$88,$33,$33,$80,$3c,$85,$88,$32
	.byte $85
@ref70:
	.byte $80,$3c,$85,$24,$85,$88,$32,$85,$80,$3c,$85,$24,$85,$3c,$85,$88
	.byte $32,$85,$80,$38,$85
@ref71:
	.byte $20,$85,$38,$85,$88,$32,$85,$80,$38,$85,$20,$85,$38,$85,$88,$32
	.byte $85,$80,$3c,$85
@ref72:
	.byte $24,$85,$3c,$85,$88,$32,$85,$80,$3c,$85,$24,$85,$3c,$85,$88,$32
	.byte $85,$80,$42,$85
@ref73:
	.byte $2a,$85,$42,$85,$88,$32,$85,$80,$46,$85,$30,$85,$48,$85,$32,$85
	.byte $4a,$85
@ref74:
	.byte $3c,$85,$24,$85,$88,$32,$85,$80,$3c,$85,$24,$85,$3c,$85,$88,$32
	.byte $85,$80,$42,$85
@ref75:
	.byte $2a,$85,$42,$85,$88,$32,$85,$80,$42,$85,$2a,$85,$42,$85,$88,$32
	.byte $85,$80,$42,$85
@ref76:
	.byte $2a,$85,$42,$85,$88,$32,$85,$80,$42,$85,$2a,$85,$42,$85,$88,$32
	.byte $85,$80,$3c,$85
@ref77:
	.byte $24,$85,$3c,$85,$88,$32,$85,$80,$3c,$85,$42,$89,$46,$89,$4a,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref78:
	.byte $86,$0c,$85,$84,$19,$19,$86,$0c,$85,$84,$19,$19,$86,$0c,$85,$84
	.byte $19,$19,$86,$0c,$85,$84,$19,$18,$81
@ref79:
	.byte $86,$0c,$85,$84,$19,$19,$86,$0c,$85,$84,$19,$19,$86,$0c,$85,$84
	.byte $19,$19,$86,$0c,$85,$0d,$0c,$81
@ref80:
	.byte $84,$04,$85,$82,$1b,$1d,$86,$0d,$82,$1d,$1a,$85,$84,$04,$85,$82
	.byte $1b,$1d,$86,$0d,$82,$1d,$1a,$85
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
@ref87:
	.byte $84,$04,$85,$82,$1b,$1d,$86,$0d,$82,$1d,$1a,$85,$84,$05,$86,$0d
	.byte $0d,$84,$1b,$86,$0d,$0d,$84,$05,$86,$0c,$81
@ref88:
	.byte $82,$04,$85,$84,$18,$85,$86,$0d,$84,$19,$82,$04,$85,$04,$85,$84
	.byte $19,$1d,$86,$0d,$84,$18,$85,$1c,$81
	.byte $ff,$11
	.word @ref88
	.byte $ff,$11
	.word @ref88
@ref91:
	.byte $82,$04,$85,$84,$18,$85,$86,$0d,$84,$19,$82,$04,$85,$04,$85,$86
	.byte $0d,$0d,$84,$1d,$19,$86,$0d,$84,$1c,$81
	.byte $ff,$11
	.word @ref88
	.byte $ff,$11
	.word @ref88
	.byte $ff,$11
	.word @ref88
	.byte $ff,$11
	.word @ref91
@ref96:
	.byte $04,$85,$82,$1b,$1d,$86,$0d,$82,$1d,$1a,$85,$84,$04,$85,$82,$1b
	.byte $1d,$86,$0d,$82,$1d,$1a,$85
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$10
	.word @ref80
	.byte $ff,$11
	.word @ref87
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref104:
	.byte $bf
@ref105:
	.byte $bf
@ref106:
	.byte $bf
@ref107:
	.byte $bf
@ref108:
	.byte $bf
@ref109:
	.byte $bf
@ref110:
	.byte $bf
@ref111:
	.byte $bf
@ref112:
	.byte $bf
@ref113:
	.byte $bf
@ref114:
	.byte $bf
@ref115:
	.byte $bf
@ref116:
	.byte $bf
@ref117:
	.byte $bf
@ref118:
	.byte $bf
@ref119:
	.byte $bf
@ref120:
	.byte $bf
@ref121:
	.byte $bf
@ref122:
	.byte $bf
@ref123:
	.byte $bf
@ref124:
	.byte $bf
@ref125:
	.byte $bf
@ref126:
	.byte $bf
@ref127:
	.byte $bf
@ref128:
	.byte $bf
@ref129:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
