;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2
@pal:
	.word @sfx_pal_0
	.word @sfx_pal_1
	.word @sfx_pal_2

@sfx_ntsc_0:
	.byte $86,$81,$87,$ab,$88,$01,$0c,$00
@sfx_pal_0:
	.byte $86,$81,$87,$8c,$88,$01,$0a,$00
@sfx_ntsc_1:
	.byte $83,$3a,$84,$54,$85,$00,$0c,$00
@sfx_pal_1:
	.byte $83,$3a,$84,$4e,$85,$00,$0a,$00
@sfx_ntsc_2:
	.byte $89,$3a,$8a,$0d,$01,$89,$39,$01,$89,$36,$0a,$00
@sfx_pal_2:
	.byte $89,$3a,$8a,$0d,$01,$89,$39,$01,$89,$36,$08,$00
